/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vian
 */
public class TugasB_ProgressBar extends javax.swing.JApplet {

    /**
     * Initializes the applet TugasB_ProgressBar
     */
    @Override
    public void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TugasB_ProgressBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TugasB_ProgressBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TugasB_ProgressBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TugasB_ProgressBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        setSize(410, 330); 
        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        counterbaru1 = new counterbaru.Counterbaru();
        counterbaru2 = new counterbaru.Counterbaru();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("VOTING UNTUK (JAVA)");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 180, -1));

        jButton2.setText("VOTING UNTUK (PHP)");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 170, -1));

        jProgressBar1.setBackground(new java.awt.Color(51, 255, 51));
        jProgressBar1.setForeground(new java.awt.Color(0, 0, 0));
        jProgressBar1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 0, 51)));
        jProgressBar1.setStringPainted(true);
        getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 370, 35));

        counterbaru1.setBackground(new java.awt.Color(0, 204, 204));
        counterbaru1.setFont(new java.awt.Font("Baskerville Old Face", 1, 12)); // NOI18N
        counterbaru1.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(counterbaru1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 180, -1));

        counterbaru2.setBackground(new java.awt.Color(0, 204, 204));
        counterbaru2.setFont(new java.awt.Font("Baskerville Old Face", 1, 12)); // NOI18N
        counterbaru2.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(counterbaru2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 170, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Obed Jeck Gredo Tarigan - 21120117120026");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 380, -1));

        jLabel5.setFont(new java.awt.Font("Leelawadee UI", 1, 16)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gredo_JT\\Documents\\NetBeansProjects\\UseComponent\\img\\icphp.png")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 170, 90));

        jLabel6.setFont(new java.awt.Font("Leelawadee UI", 1, 16)); // NOI18N
        jLabel6.setText("Vote Untuk Bahasa Pemrograman Favorit Kamu!");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 390, 30));

        jLabel7.setFont(new java.awt.Font("Leelawadee UI", 1, 16)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gredo_JT\\Documents\\NetBeansProjects\\UseComponent\\img\\iconjava.png")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 160, 90));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
counterbaru1.increment();

float voteJAVA = Float.parseFloat(counterbaru1.getvalue());
float votePHP = Float.parseFloat(counterbaru2.getvalue());

float total = voteJAVA + votePHP;
float pembagian = (voteJAVA/total);
float persen = pembagian*100;

jProgressBar1.setValue((int)persen);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
counterbaru2.increment(); 
float voteJAVA = Float.parseFloat(counterbaru1.getvalue());
float votePHP = Float.parseFloat(counterbaru2.getvalue());

float total = voteJAVA + votePHP;
float pembagian = (voteJAVA/total);
float persen = pembagian*100;

jProgressBar1.setValue((int)persen); 
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private counterbaru.Counterbaru counterbaru1;
    private counterbaru.Counterbaru counterbaru2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
